### ISSUE TITLE
Error with .mov and .mp4

### ISSUE THREAD

**Issue by Lastofthefirst** [realdennis/video2gif#13]
Love it! I get an error when I dropped a .mov or .mp4 file on the screen. Also happened when I selected from filesystem. No errors appear in the console.

<img width="949" alt="Screen Shot 2021-03-25 at 4 21 29 PM" src="https://user-images.githubusercontent.com/47003973/112538359-29b82480-8d86-11eb-8407-96ae8b9e8586.png">

**Comment by x3388638** [comment]
try the latest Chrome

ref: https://github.com/ffmpegwasm/ffmpeg.wasm/issues/102
cc @realdennis
